language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='^2.8'
    - php: 7.2
      env: SYMFONY_VERSION='^2.8'
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.3
      env: SYMFONY_VERSION='^4.0'

before_install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'

before_script:
  - composer update

script:
  - phpunit
